# Generated by Django 3.1 on 2021-03-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
