# Generated by Django 3.1.7 on 2021-04-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_userprofile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='title',
        ),
    ]
