# Generated by Django 3.1.7 on 2021-04-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_remove_userprofile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
