# Generated by Django 3.1.7 on 2021-04-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_auto_20210408_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
