# Generated by Django 3.1 on 2021-04-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0034_auto_20210420_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
