# Generated by Django 3.1 on 2021-04-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0035_auto_20210421_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
