# Generated by Django 3.1 on 2021-04-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0036_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
