# Generated by Django 3.1 on 2021-04-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0038_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(default='remaining', max_length=50),
        ),
    ]
